spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

server:
  port: 8080

application:
  message: "Test Props msg"
  locale: ru_RU
