spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: fdec09b924be7f214eaa
            clientSecret: 5436beb72dc2ec7f2320afcab5185c1ea03d484b

logging:
  level:
    root: error
    org.springframework.security: DEBUG